export const indianStates = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Lakshadweep",
    "Puducherry",
    "Ladakh",
    "Jammu and Kashmir"
  ];
  

  export const technologies=[
      "React.js",
      "Angular",
      "Vue.js",
      "Node.js",
      "Express.js",
      "Flask",
      "Laravel",
      "ASP.NET",
      "jQuery",
      "Bootstrap",
      "Tailwind CSS",
      "Material-UI",
      "Sass",
      "REST API",
      "Babel",
      "TypeScript",
      "JavaScript",
      "Python",
      "Java",
      "PHP",

    
  ]